CREATE TABLE shops(
   SHOP_ID   INTEGER  NOT NULL PRIMARY KEY 
  ,SHOP_NAME VARCHAR(24) NOT NULL
);
INSERT INTO shops(SHOP_ID,SHOP_NAME) VALUES (485857,'Disney Store');
INSERT INTO shops(SHOP_ID,SHOP_NAME) VALUES (962418,'Hollywood Store');
INSERT INTO shops(SHOP_ID,SHOP_NAME) VALUES (347774,'Bollywood Store');
INSERT INTO shops(SHOP_ID,SHOP_NAME) VALUES (186404,'Baby /looney Tunes Store');
INSERT INTO shops(SHOP_ID,SHOP_NAME) VALUES (695824,'Pirates Store');
INSERT INTO shops(SHOP_ID,SHOP_NAME) VALUES (723822,'Horror Store');
INSERT INTO shops(SHOP_ID,SHOP_NAME) VALUES (889171,'Waterworld Store');
INSERT INTO shops(SHOP_ID,SHOP_NAME) VALUES (586911,'Fairy Tales Store');
INSERT INTO shops(SHOP_ID,SHOP_NAME) VALUES (210503,'Legoland Store');
INSERT INTO shops(SHOP_ID,SHOP_NAME) VALUES (282930,'Superheroes Store');
INSERT INTO shops(SHOP_ID,SHOP_NAME) VALUES (225802,'Sports Store');
INSERT INTO shops(SHOP_ID,SHOP_NAME) VALUES (675335,'Cowboys Store');
INSERT INTO shops(SHOP_ID,SHOP_NAME) VALUES (845797,'Space Store');
INSERT INTO shops(SHOP_ID,SHOP_NAME) VALUES (731040,'Adventure Store');
INSERT INTO shops(SHOP_ID,SHOP_NAME) VALUES (784125,'Sci-Fi Store');
